name: finalproject
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2
  video_player: ^2.9.3
  table_calendar: ^3.2.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/
    - assets/audio/umbrella.mp3
    - assets/audio/banana.mp3
    - assets/audio/phone.mp3